FROM consul:1.6.0-beta1

FROM envoyproxy/envoy-alpine:v1.10.0

COPY --from=0 /bin/consul /usr/local/bin/consul

COPY ./wait_for_consul.sh /wait_for_consul.sh
RUN chmod +x /wait_for_consul.sh

ENTRYPOINT ["/wait_for_consul.sh"]
