FROM envoyproxy/envoy-alpine:v1.10.0

RUN wget https://releases.hashicorp.com/consul/1.6.0-beta2/consul_1.6.0-beta2_linux_amd64.zip -O /tmp/consul.zip
RUN unzip /tmp/consul.zip -d /tmp
RUN mv /tmp/consul /usr/local/bin/consul

COPY ./wait_for_consul.sh /wait_for_consul.sh
RUN chmod +x /wait_for_consul.sh

ENTRYPOINT ["/wait_for_consul.sh"]
