# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "3.3"
services:

  consul:
    build:
      context: .
      dockerfile: Dockerfile-consul
    command: ["consul","agent","-config-file=/config/consul.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/upstream-echo:v0.1.8
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_ADDR: localhost:9991
      UPSTREAM_CALL: "true"
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.7.2-v1.14.2
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web.json
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:web"

  # Define api service and envoy sidecar proxy for version 1 of the service
  api_v1:
    image: nicholasjackson/upstream-echo:v0.1.8
    environment:
      LISTEN_ADDR: localhost:9090
      MESSAGE: "Service V1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  api_proxy_v1:
    image: nicholasjackson/consul-envoy:v1.7.2-v1.14.2
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v1.json
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v1"]
    network_mode: "service:api_v1"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
